version: '2'
services:
    myweb-app:
        image: myweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://myweb-postgresql:5432/MyWeb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myweb-postgresql:
        extends:
            file: postgresql.yml
            service: myweb-postgresql
