version: '2'
services:
    myweb-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/MyWeb/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=MyWeb
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
